### ISSUE TITLE
Team-block

### ISSUE THREAD

**Issue by Clarissa0512** [cosola-macile/macile.org#36]
### Vision

- Crear una sección que contenga una imagen y un nombre debajo, añadiendo el contenido desde un yml.

### Scope

- [x] Crear una carpeta en modules para poner el html de team.
- [x] Crear el archivo de html de team.
- [x] Crear los yml de team en ES y EN.
- [x] Añadirlo a about.

### Anti-Vision

- No poner el contenido en html.

**Comment by misscs** [comment]
#37
