### ISSUE TITLE
Crear páginas básicas de news y becas

### ISSUE THREAD

**Issue by Morban15** [cosola-macile/macile.org#7]
### Vision
Crear páginas básicas para becas y noticias en español e inglés

### Scope

What is required to consider this feature-complete?

- [x] Crear una carpeta en views con el nombre de la página.
- En este caso serían dos carpetas con los nombres "becas" y "news".
- [x] Crear el archivo index.html  y colocarlos en sus carpetas
- [x] Agregar los archivos a yml en inglés y en español
- Añadir commits para cada  página

### Anti-Vision

What is out of scope or goes against the original intention?

Que las páginas no se traduzcan en ninguno de los dos idiomas.

**Comment by misscs** [comment]
Muy bien! El Pull request de becas #9

**Comment by misscs** [comment]
PR closed!
