### ISSUE TITLE
Añadir la sección overview a Summer Academy en español

### ISSUE THREAD

**Issue by Morban15** [cosola-macile/macile.org#82]
### Vision
En Summer Academy en español. En el intern_nav está el link de overview,
pero esa sección no está en la página en español. Y Summer Academy debe tener el mismo contenido en español e inglés, por lo tanto hay que añadirla. 

### Current State

What is currently implemented (or not implemented)?

### Scope

What is required to consider this feature-complete?

### Anti-Vision

What is out of scope or goes against the original intention?

**Comment by cosola** [comment]
Maria, I am working on  this one. If I need your help, will ask.

**Comment by cosola** [comment]
@Morban15
