### ISSUE TITLE
Quitar los links a los títulos de Sessions en Summer Academy

### ISSUE THREAD

**Issue by Morban15** [cosola-macile/macile.org#84]
### Vision
Hay que cambiar de link a título en content_panel para Sessions en Summer Academy.
Por ahora sólo tienen que ser título solamente y no links para cada sección.

### Current State

What is currently implemented (or not implemented)?

### Scope

What is required to consider this feature-complete?

### Anti-Vision

What is out of scope or goes against the original intention?

**Comment by Morban15** [comment]
Voy a trabajar en este (Quitar los links a los títulos de Sessions en Summer Academy)

**Comment by misscs** [comment]
Asignalo a ti mismo

**Comment by Morban15** [comment]
ya

**Comment by misscs** [comment]
muy bien! gracias

**Comment by cosola** [comment]
@Morban15, corregi el problema :raised_hands:  Voy a abrir un pull request para que le revise y apruebe

**Comment by cosola** [comment]
@Morban15 , creo que esta tarea puede cerrarse. Hay algo aun pendiente?

**Comment by Morban15** [comment]
Para esto no 🥇. Lo voy a cerrar
